### ISSUE TITLE
Make it work on mobile

### ISSUE THREAD

**Issue by AlexGilleran** [RHoKAustralia/watch-me-grow#27]
Was trying to demo it tonight at RHoK ideation and holy hell does it work badly on anything smaller than a tablet.

**Comment by dvincent** [comment]
One simple test for desktop is to visit the site in some browser, make the window as narrow as possible, and see what looks wrong.

In Chrome "Version 49.0.2623.112 (64-bit)" on Mac OS X 10.7 Lion, that width is 400 pixels.
