### ISSUE TITLE
Hide/remove signup button from the header

### ISSUE THREAD

**Issue by dvincent** [RHoKAustralia/watch-me-grow#30]
As discussed around 4:45pm, 4 June 2016.  And https://rhoksydney.slack.com/archives/watch-me-grow/p1465023268000009

**Comment by dvincent** [comment]
Is this "signup" as on Slack?  or "Sign In"?  That is, Sign In as we see when we move the mouse over the little head and shoulders icon in the title bar thing.

**Comment by AlexGilleran** [comment]
Doesn't really matter, we're killing everything remotely login related 🔫 😄

**Comment by dvincent** [comment]
OK.  But stop waving that pistol around.  :)
